---
- name: Install Tor proxy
  ansible.builtin.apt:
    name: tor
    state: present

# --- Architecture-specific Tor Browser installation ---
- name: Include amd64 Tor Browser tasks
  ansible.builtin.include_tasks: amd64.yml
  when: dpkg_arch == 'amd64'

- name: Include arm64 Tor Browser tasks
  ansible.builtin.include_tasks: arm64.yml
  when: dpkg_arch != 'amd64'
